version: "3"
services:
  application-base:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: application-base
    ports:
      - 8001:3000
    volumes:
      - .:/usr/src/app
    networks:
      - application-base-network
    restart: unless-stopped

  nginx-base:
    container_name: nginx-base
    image: nginx:1.17.8
    ports:
      - 80:80
    volumes:
      - ./conf:/etc/nginx/conf.d
      - /etc/hosts:/etc/hosts
    links:
      - application-base
    networks:
      - application-base-network
    depends_on:
      - application-base
    restart: unless-stopped

networks:
  application-base-network:
    driver: bridge
